# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapsizer/Ui_MapSizer.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MapSizer(object):
    def setupUi(self, MapSizer):
        MapSizer.setObjectName("MapSizer")
        MapSizer.setWindowModality(QtCore.Qt.WindowModal)
        MapSizer.resize(587, 290)
        MapSizer.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.spinBoxImageWidth = QtWidgets.QSpinBox(MapSizer)
        self.spinBoxImageWidth.setGeometry(QtCore.QRect(167, 10, 124, 26))
        self.spinBoxImageWidth.setMinimum(150)
        self.spinBoxImageWidth.setMaximum(15000)
        self.spinBoxImageWidth.setSingleStep(50)
        self.spinBoxImageWidth.setProperty("value", 400)
        self.spinBoxImageWidth.setObjectName("spinBoxImageWidth")
        self.spinBoxImageHeight = QtWidgets.QSpinBox(MapSizer)
        self.spinBoxImageHeight.setGeometry(QtCore.QRect(297, 10, 127, 26))
        self.spinBoxImageHeight.setMinimum(150)
        self.spinBoxImageHeight.setMaximum(15000)
        self.spinBoxImageHeight.setSingleStep(50)
        self.spinBoxImageHeight.setProperty("value", 400)
        self.spinBoxImageHeight.setObjectName("spinBoxImageHeight")
        self.btnSetImageSize = QtWidgets.QPushButton(MapSizer)
        self.btnSetImageSize.setGeometry(QtCore.QRect(430, 10, 124, 27))
        self.btnSetImageSize.setObjectName("btnSetImageSize")
        self.lblSetImageSize = QtWidgets.QLabel(MapSizer)
        self.lblSetImageSize.setGeometry(QtCore.QRect(20, 10, 141, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSetImageSize.sizePolicy().hasHeightForWidth())
        self.lblSetImageSize.setSizePolicy(sizePolicy)
        self.lblSetImageSize.setObjectName("lblSetImageSize")
        self.lblSetExtent = QtWidgets.QLabel(MapSizer)
        self.lblSetExtent.setGeometry(QtCore.QRect(20, 90, 141, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSetExtent.sizePolicy().hasHeightForWidth())
        self.lblSetExtent.setSizePolicy(sizePolicy)
        self.lblSetExtent.setObjectName("lblSetExtent")
        self.btnSetExtent = QtWidgets.QPushButton(MapSizer)
        self.btnSetExtent.setGeometry(QtCore.QRect(430, 150, 124, 27))
        self.btnSetExtent.setObjectName("btnSetExtent")
        self.txtMaxY = QtWidgets.QLineEdit(MapSizer)
        self.txtMaxY.setGeometry(QtCore.QRect(240, 100, 101, 26))
        self.txtMaxY.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.txtMaxY.setObjectName("txtMaxY")
        self.lblMaxX = QtWidgets.QLabel(MapSizer)
        self.lblMaxX.setGeometry(QtCore.QRect(280, 150, 51, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMaxX.sizePolicy().hasHeightForWidth())
        self.lblMaxX.setSizePolicy(sizePolicy)
        self.lblMaxX.setObjectName("lblMaxX")
        self.lblMinX = QtWidgets.QLabel(MapSizer)
        self.lblMinX.setGeometry(QtCore.QRect(110, 150, 51, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMinX.sizePolicy().hasHeightForWidth())
        self.lblMinX.setSizePolicy(sizePolicy)
        self.lblMinX.setObjectName("lblMinX")
        self.lblMinY = QtWidgets.QLabel(MapSizer)
        self.lblMinY.setGeometry(QtCore.QRect(200, 210, 51, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMinY.sizePolicy().hasHeightForWidth())
        self.lblMinY.setSizePolicy(sizePolicy)
        self.lblMinY.setObjectName("lblMinY")
        self.lblMaxY = QtWidgets.QLabel(MapSizer)
        self.lblMaxY.setGeometry(QtCore.QRect(200, 100, 51, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMaxY.sizePolicy().hasHeightForWidth())
        self.lblMaxY.setSizePolicy(sizePolicy)
        self.lblMaxY.setObjectName("lblMaxY")
        self.txtMinY = QtWidgets.QLineEdit(MapSizer)
        self.txtMinY.setGeometry(QtCore.QRect(240, 210, 101, 26))
        self.txtMinY.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.txtMinY.setObjectName("txtMinY")
        self.txtMinX = QtWidgets.QLineEdit(MapSizer)
        self.txtMinX.setGeometry(QtCore.QRect(150, 150, 101, 26))
        self.txtMinX.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.txtMinX.setObjectName("txtMinX")
        self.txtMaxX = QtWidgets.QLineEdit(MapSizer)
        self.txtMaxX.setGeometry(QtCore.QRect(320, 150, 101, 26))
        self.txtMaxX.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.txtMaxX.setObjectName("txtMaxX")
        self.line = QtWidgets.QFrame(MapSizer)
        self.line.setGeometry(QtCore.QRect(80, 60, 411, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.buttonBox = QtWidgets.QDialogButtonBox(MapSizer)
        self.buttonBox.setGeometry(QtCore.QRect(10, 250, 559, 27))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(MapSizer)
        QtCore.QMetaObject.connectSlotsByName(MapSizer)

    def retranslateUi(self, MapSizer):
        _translate = QtCore.QCoreApplication.translate
        MapSizer.setWindowTitle(_translate("MapSizer", "Form"))
        self.spinBoxImageWidth.setSuffix(_translate("MapSizer", " px"))
        self.spinBoxImageWidth.setPrefix(_translate("MapSizer", "Width "))
        self.spinBoxImageHeight.setSuffix(_translate("MapSizer", " px"))
        self.spinBoxImageHeight.setPrefix(_translate("MapSizer", "Height "))
        self.btnSetImageSize.setText(_translate("MapSizer", "Set"))
        self.lblSetImageSize.setText(_translate("MapSizer", "Set Map/Image size"))
        self.lblSetExtent.setText(_translate("MapSizer", "Set Extent (bbox)"))
        self.btnSetExtent.setText(_translate("MapSizer", "Set"))
        self.lblMaxX.setText(_translate("MapSizer", "max X"))
        self.lblMinX.setText(_translate("MapSizer", "min X"))
        self.lblMinY.setText(_translate("MapSizer", "min Y"))
        self.lblMaxY.setText(_translate("MapSizer", "max Y"))

