# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapsizer/Ui_MapSizer.ui'
#
# Created: Sat Feb  4 14:15:45 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MapSizer(object):
    def setupUi(self, MapSizer):
        MapSizer.setObjectName(_fromUtf8("MapSizer"))
        MapSizer.setWindowModality(QtCore.Qt.WindowModal)
        MapSizer.resize(574, 292)
        MapSizer.setWindowTitle(QtGui.QApplication.translate("MapSizer", "Form", None, QtGui.QApplication.UnicodeUTF8))
        MapSizer.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.spinBoxImageWidth = QtGui.QSpinBox(MapSizer)
        self.spinBoxImageWidth.setGeometry(QtCore.QRect(167, 10, 124, 26))
        self.spinBoxImageWidth.setSuffix(QtGui.QApplication.translate("MapSizer", " px", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxImageWidth.setPrefix(QtGui.QApplication.translate("MapSizer", "Width ", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxImageWidth.setMinimum(150)
        self.spinBoxImageWidth.setMaximum(15000)
        self.spinBoxImageWidth.setSingleStep(50)
        self.spinBoxImageWidth.setProperty("value", 400)
        self.spinBoxImageWidth.setObjectName(_fromUtf8("spinBoxImageWidth"))
        self.spinBoxImageHeight = QtGui.QSpinBox(MapSizer)
        self.spinBoxImageHeight.setGeometry(QtCore.QRect(297, 10, 127, 26))
        self.spinBoxImageHeight.setSuffix(QtGui.QApplication.translate("MapSizer", " px", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxImageHeight.setPrefix(QtGui.QApplication.translate("MapSizer", "Height ", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxImageHeight.setMinimum(150)
        self.spinBoxImageHeight.setMaximum(15000)
        self.spinBoxImageHeight.setSingleStep(50)
        self.spinBoxImageHeight.setProperty("value", 400)
        self.spinBoxImageHeight.setObjectName(_fromUtf8("spinBoxImageHeight"))
        self.btnSetImageSize = QtGui.QPushButton(MapSizer)
        self.btnSetImageSize.setGeometry(QtCore.QRect(430, 10, 124, 27))
        self.btnSetImageSize.setText(QtGui.QApplication.translate("MapSizer", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetImageSize.setObjectName(_fromUtf8("btnSetImageSize"))
        self.lblSetImageSize = QtGui.QLabel(MapSizer)
        self.lblSetImageSize.setGeometry(QtCore.QRect(20, 10, 141, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSetImageSize.sizePolicy().hasHeightForWidth())
        self.lblSetImageSize.setSizePolicy(sizePolicy)
        self.lblSetImageSize.setText(QtGui.QApplication.translate("MapSizer", "Set Map/Image size", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSetImageSize.setObjectName(_fromUtf8("lblSetImageSize"))
        self.lblSetExtent = QtGui.QLabel(MapSizer)
        self.lblSetExtent.setGeometry(QtCore.QRect(20, 90, 141, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSetExtent.sizePolicy().hasHeightForWidth())
        self.lblSetExtent.setSizePolicy(sizePolicy)
        self.lblSetExtent.setText(QtGui.QApplication.translate("MapSizer", "Set Extent (bbox)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSetExtent.setObjectName(_fromUtf8("lblSetExtent"))
        self.btnSetExtent = QtGui.QPushButton(MapSizer)
        self.btnSetExtent.setGeometry(QtCore.QRect(430, 150, 124, 27))
        self.btnSetExtent.setText(QtGui.QApplication.translate("MapSizer", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetExtent.setObjectName(_fromUtf8("btnSetExtent"))
        self.txtMaxY = QtGui.QLineEdit(MapSizer)
        self.txtMaxY.setGeometry(QtCore.QRect(240, 100, 101, 26))
        self.txtMaxY.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.txtMaxY.setObjectName(_fromUtf8("txtMaxY"))
        self.lblMaxX = QtGui.QLabel(MapSizer)
        self.lblMaxX.setGeometry(QtCore.QRect(280, 150, 51, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMaxX.sizePolicy().hasHeightForWidth())
        self.lblMaxX.setSizePolicy(sizePolicy)
        self.lblMaxX.setText(QtGui.QApplication.translate("MapSizer", "max X", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMaxX.setObjectName(_fromUtf8("lblMaxX"))
        self.lblMinX = QtGui.QLabel(MapSizer)
        self.lblMinX.setGeometry(QtCore.QRect(110, 150, 51, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMinX.sizePolicy().hasHeightForWidth())
        self.lblMinX.setSizePolicy(sizePolicy)
        self.lblMinX.setText(QtGui.QApplication.translate("MapSizer", "min X", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMinX.setObjectName(_fromUtf8("lblMinX"))
        self.lblMinY = QtGui.QLabel(MapSizer)
        self.lblMinY.setGeometry(QtCore.QRect(200, 210, 51, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMinY.sizePolicy().hasHeightForWidth())
        self.lblMinY.setSizePolicy(sizePolicy)
        self.lblMinY.setText(QtGui.QApplication.translate("MapSizer", "min Y", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMinY.setObjectName(_fromUtf8("lblMinY"))
        self.lblMaxY = QtGui.QLabel(MapSizer)
        self.lblMaxY.setGeometry(QtCore.QRect(200, 100, 51, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMaxY.sizePolicy().hasHeightForWidth())
        self.lblMaxY.setSizePolicy(sizePolicy)
        self.lblMaxY.setText(QtGui.QApplication.translate("MapSizer", "max Y", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMaxY.setObjectName(_fromUtf8("lblMaxY"))
        self.txtMinY = QtGui.QLineEdit(MapSizer)
        self.txtMinY.setGeometry(QtCore.QRect(240, 210, 101, 26))
        self.txtMinY.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.txtMinY.setObjectName(_fromUtf8("txtMinY"))
        self.txtMinX = QtGui.QLineEdit(MapSizer)
        self.txtMinX.setGeometry(QtCore.QRect(150, 150, 101, 26))
        self.txtMinX.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.txtMinX.setObjectName(_fromUtf8("txtMinX"))
        self.txtMaxX = QtGui.QLineEdit(MapSizer)
        self.txtMaxX.setGeometry(QtCore.QRect(320, 150, 101, 26))
        self.txtMaxX.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.txtMaxX.setObjectName(_fromUtf8("txtMaxX"))
        self.line = QtGui.QFrame(MapSizer)
        self.line.setGeometry(QtCore.QRect(80, 60, 411, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.buttonBox = QtGui.QDialogButtonBox(MapSizer)
        self.buttonBox.setGeometry(QtCore.QRect(10, 250, 559, 27))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))

        self.retranslateUi(MapSizer)
        QtCore.QMetaObject.connectSlotsByName(MapSizer)

    def retranslateUi(self, MapSizer):
        pass

